Front end for book saving
kedar-damle/EthicalEating-TheCoasters pull request #24
Opened 2020-11-12 22:12 UTC by troyjholt

Added some front end book saving functionality.
User books populate dynamically now. They can create new books now.

2020-11-13 11:59 UTC, kedar-damle requested changes
1. Cannot create a new book when I click "Add New Book"

2. Seeing this error in console after loading the page

```
Uncaught TypeError: closeButton is null
    <anonymous> http://localhost:50902/js/pop_up.js:19
```
Tested on :
Chrome 86 Windows 10
Firefox 82 Linux

2020-11-16 22:24 UTC, troyjholt commented
Fixed modal not popping up and allowing user to create a new book.

2020-11-17 13:39 UTC, alcaidet commented
I can see the modals pop up when I click "+Add New Book" on the sidebar and also "+New Book" from the 3-dot menu.

2020-11-17 13:39 UTC, alcaidet approved these changes

2020-11-17 17:49 UTC, merged